CreacionesPajov/CreacionesPajov/Models/Entities/Produccion.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CreacionesPajov.WEB.Models.Entities
{
    public class Produccion
    {

        public Produccion()
        {

            DetalleLotes = new HashSet<DetalleLote>();
        }


        public int ProduccionId { get; set; }

        [Required(ErrorMessage = "El Nombre es Obligatorio")]
        [StringLength(50, ErrorMessage = "El {0} debe tener al menos {2} y máximo {1} caracteres", MinimumLength = 3)]
        [Display(Name = "Nombre")]
        public string Nombre { get; set; }

        public int Total { get; set; }

        [Required(ErrorMessage = "La descrición es Obligatoria")]
        [StringLength(200, ErrorMessage = "El {0} debe tener al menos {2} y máximo {1} caracteres", MinimumLength = 3)]
        [Display(Name = "Descripción")]
        public string Descripcion { get; set; }

        public DateTime FechaRegistro { get; set; } = DateTime.Now;

        [Required(ErrorMessage = "La Fecha de salida es Obligatoria")]
        public DateTime FechaSalida { get; set; }

        public bool Estado { get; set; }

        [Required(ErrorMessage = "La fase es requerida")]
        [Display(Name = "Fase")]
        public int? FaseId { get; set; }

        public virtual Fase Fases { get; set; }

        

        public virtual ICollection<DetalleLote> DetalleLotes { get; set; }



    }
}

CreacionesPajov/CreacionesPajov/Controllers/ProduccionController.cs
using CreacionesPajov.WEB.Helpers;
using CreacionesPajov.WEB.Models.Abstract;
using CreacionesPajov.WEB.Models.Abstract.IProduccion;
using CreacionesPajov.WEB.Models.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using static CreacionesPajov.WEB.Helpers.Helper;

namespace CreacionesPajov.WEB.Controllers
{
    public class ProduccionController : Controller
    {
        private readonly IProduccionService _produccionService;
        private readonly IFaseService _faseService;

        public ProduccionController(IProduccionService produccionService, IFaseService faseService)
        {
            _produccionService = produccionService; //inyectamos la interfaz empleadoService.
            _faseService = faseService;
        }
        public async Task<IActionResult> Index()
        {
            @ViewBag.Titulo = "Producción";
            ViewBag.Fases = new SelectList(await _faseService.ObtenerFases(), "FaseId", "Nombre");
            var producion = await _produccionService.ObtenerProduccion();
            return View(producion);
        }

        [HttpGet]
        //[NoDirectAccess]
        public async Task<IActionResult> Crear()
        {


            try
            {
                ViewBag.Titulo = "Crear Producción";
                ViewBag.Fases = new SelectList(await _faseService.ObtenerFases(), "FaseId", "Nombre");

                ViewBag.Produccion = new SelectList(await _produccionService.ObtenerProduccion(), "Nombre");
                return View();
            }
            catch (Exception)
            {
                return Json(new { isValid = false, tipoError = "error", mensaje = "Error interno al crear el registro." });

            }


        }
        [HttpPost]

        public async Task<IActionResult> CrearAsync(Produccion produccion)
        {
            if (produccion == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _produccionService.Crear(produccion);
                    var guardar = await _produccionService.GuardarCambios();
                    if (guardar)
                    {

                   
                        return Json(new { isValid = true, operacion = "crear" });
                    }
                    else
                        return Json(new { isValid = false, tipoError = "error", mensaje = "Error interno al crear el registro." });



                }
                catch (Exception)
                {

                    return Json(new { isValid = false, tipoError = "error", mensaje = "Error interno al crear el registro." });
                }

            }
            ViewBag.Titulo = "Crear producción";
         
            return Json(new { isValid = false, tipoError = "warning", error = "Debe diligenciar los campos requeridos.", html = Helper.RenderRazorViewToString(this, "Crear", produccion) });
        }

        [HttpGet]

        public async Task<IActionResult> Editar(int? id)
        {
            if (id != null)
            {
                try
                {
                    ViewBag.Fases = new SelectList(await _faseService.ObtenerFases(), "FaseId", "Nombre");
                    var produccion = await _produccionService.ObtenerProduccionPorId(id.Value);
                    if (produccion != null)
                    {

                        ViewBag.Produccion = new SelectList(await _produccionService.ObtenerProduccion(), "Nombre");

                        return View(produccion);
                    }
                    else
                        return NotFound();
                }
                catch (Exception)
                {

                    throw;
                }
            }
            return NotFound();

        }
        [HttpPost]

        public async Task<IActionResult> Editar(int? id, Produccion produccion)
        {
            if (id != produccion.ProduccionId)
                return Json(new { isValid = false, tipoError = "error", mensaje = "Error interno al editar el registro." });

            if (ModelState.IsValid)
            {
                try
                {
                    _produccionService.Editar(produccion);
                    var editar = await _produccionService.GuardarCambios();
                    if (editar)
                        return Json(new { isValid = true, operacion = "editar" });

                    else
                        return Json(new { isValid = false, tipoError = "error", mensaje = "Error interno al editar el registro." });

                }
                catch (Exception)
                {

                    return Json(new { isValid = false, tipoError = "error", mensaje = "Error interno al editar el registro." });

                }
            }
            //Si el modelo tiene errores en las validadciones
            ViewBag.Titulo = "Editar  producción";
            ViewBag.Produccion = new SelectList(await _produccionService.ObtenerProduccion(), "Nombre");
            return Json(new { isValid = false, tipoError = "warning", error = "Debe diligenciar los campos requeridos.", html = Helper.RenderRazorViewToString(this, "Editar", produccion) });




        }

       [HttpGet]

        public async Task<IActionResult> Detalle(int? id)
        {
            if (id != null)
            {
                try
                {
                    ViewBag.Fases = new SelectList(await _faseService.ObtenerFases(), "FaseId", "Nombre");
                    var produccion = await _produccionService.ObtenerProduccionPorId(id.Value);
                    if (produccion != null)
                        return View(produccion);
                    else
                        return Json(new { isValid = false, tipoError = "error", mensaje = "Error  al consultar el registro." });

                }
                catch (Exception)
                {

                    return Json(new { isValid = false, tipoError = "error", mensaje = "Error interno al consultar el registro." });

                }
            }
            return Json(new { isValid = false, tipoError = "error", mensaje = "Error  al consultar el registro." });

        }
        [HttpGet]

        public async Task<IActionResult> CambiarEstado(int? id)
        {
            if (id != null)
            {
                try
                {
                    var produccion = await _produccionService.ObtenerProduccionPorId(id.Value);
                    if (produccion != null)
                    {
                        produccion.Estado = !produccion.Estado;
                        _produccionService.Editar(produccion);
                        var editar = await _produccionService.GuardarCambios();
                        if (editar)
                            return Json(new { isValid = true, });
                    }


                    else
                        return Json(new { isValid = false, });
                }
                catch (Exception)
                {

                    return Json(new { isValid = false, tipoError = "error", mensaje = "Error interno al consultar el registro." });

                }
            }
            return Json(new { isValid = false, tipoError = "error", mensaje = "Error  al consultar el registro." });

        }



    }

}

CreacionesPajov/CreacionesPajov/Views/Produccion/Crear.cshtml
@model CreacionesPajov.WEB.Models.Entities.Produccion
@{Layout = null; }

<style>
    span.text-danger.field-validation-error, #Nombre-error, #Descripcion-error, #FechaSalida-error {
        font-size: 12px;
    }
</style>

<body style="background-color: #eee;">
    <br />
    <div>
        <form asp-action="Crear" id="formulario" onsubmit="return jQueryAjaxPost (this, 'Crear Producción','¿Desea crear una nueva producción?'); ">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="row">
                <div class="column">
                    <div class="form-group">
                        <label asp-for="Nombre" class="control-label"></label>
                        <input type="text" asp-for="Nombre" class="input-crear form-control" />
                        <span asp-validation-for="Nombre" class="text-danger"></span>
                    </div>
                </div>
                <div class="column">
                    <div class="form-group column2">
                        <label asp-for="Descripcion" class="control-label"></label>
                        <input type="text" asp-for="Descripcion" class="input-crear form-control" />
                        <span asp-validation-for="Descripcion" class="text-danger"></span>
                    </div>
                </div>
            </div>

    
            <div class="row">
            <div class=" form-group">
                <label asp-for="FaseId" class="control-label"></label>
                <select asp-for="FaseId" asp-items="ViewBag.Fases" class="input-crear-td form-control">
                    <option disabled selected>----Seleccione----</option>
                </select>
                <span asp-validation-for="FaseId" class="text-danger"></span>
            </div>
        </div>

            @*<div class="row">
            <div class="form-group ">
                <label asp-for="FechaSalida" class="control-label"></label>
                <input type="date" asp-for="FechaSalida" class="input-crear form-control" />
                <span asp-validation-for="FechaSalida" class="text-danger"></span>
            </div>
        </div>*@

            <br />
            <div class="form-group">
                <center>
                    <input type="submit" value="Guardar" class="btn boton-crear" />
                </center>

            </div>
            <br />
        </form>
    </div>

</body>


@*<form asp-action="Crear">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="from-group">
            <label asp-for="Nombre" class="control-label"></label>
            <input type="text" asp-for="Nombre" class="form-control"/>
            <span asp-validation-for="Nombre" class="text-danger"></span>
        </div>
    </form>*@
<script src="~/js/site.js"></script>
@await Html.PartialAsync("_ValidationScriptsPartial")

CreacionesPajov/CreacionesPajov/Views/Produccion/Detalle.cshtml
@model CreacionesPajov.WEB.Models.Entities.Produccion
@{
    Layout = null;
}
<body style="background-color: #eee;">
    <form>
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <center>
            <br />
            <table style="width:650px;" class="detalle table-striped">
                <tbody>
                    <tr>
                        <td><label asp-for="Nombre" class="control-label"></label></td>
                        <td><div class="model-detalle">@Model.Nombre </div></td>
                    </tr>
                    <tr>
                        <td><label asp-for="Descripcion" class="control-label"></label></td>
                        <td><div class="model-detalle">@Model.Descripcion </div></td>
                    </tr>
                    <tr>
                        <td><label asp-for="FechaRegistro" class="control-label"></label></td>
                        <td><div class="model-detalle">@Model.FechaRegistro</div></td>
                    </tr>
                    <tr>
                        <td><label asp-for="FaseId" class="control-label"></label></td>
                        <td><div class="model-detalle">@Model.Fases.Nombre</div></td>
                    </tr>
                    @*<tr>
            <td><label asp-for="Fases" class="control-label"></label></td>
            <td><div class="model-detalle">@Model.Fases</div></td>
        </tr>*@
                    <tr>
                        <td><label asp-for="FechaSalida" class="control-label"></label></td>
                        <td><div class="model-detalle">@Model.FechaSalida</div></td>
                    </tr>
                </tbody>
            </table><br />
        </center>
    </form>
</body>

<script src="~/js/site.js"></script>
@await Html.PartialAsync("_ValidationScriptsPartial")

CreacionesPajov/CreacionesPajov/Views/Produccion/Editar.cshtml
@model CreacionesPajov.WEB.Models.Entities.Produccion
@{ Layout = null; }


<h1>@ViewBag.Titulo</h1>
<br />

<style>
    span.text-danger.field-validation-error, #Nombre-error, #Descripcion-error, #FechaSalida-error {
        font-size: 12px;
    }
</style>

<input type="hidden" asp-for="ProduccionId" />
<input type="hidden" asp-for="Estado" />

<body style="background-color: #eee;">

    <form asp-action="Editar" id="formulario" onsubmit="return jQueryAjaxPost(this, 'Editar Produccion','¿Desea Editar la producción?'); ">

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="row">
            <div class="column">
                <div class="form-group">
                    <label asp-for="Nombre" class="control-label"></label>
                    <input type="hidden" asp-for="ProduccionId" />
                    <input type="text" asp-for="Nombre" class="input-editar form-control" />
                    <span asp-validation-for="Nombre" class="text-danger"></span>
                </div>
            </div>
            <div class="column">
                <div class="form-group column2">
                    <label asp-for="FechaRegistro" class="control-label"></label>
                    <input type="date" asp-for="FechaRegistro" class="input-editar form-control" />
                    <span asp-validation-for="FechaRegistro" class="text-danger"></span>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="column">
                <div class="form-group ">
                    <label asp-for="FechaSalida" class="control-label"></label>
                    <input type="date" asp-for="FechaSalida" class="input-editar form-control" />
                    <span asp-validation-for="FechaSalida" class="text-danger"></span>
                </div>
            </div>
            <div class="column">
                <div class="form-group column2">
                    <label asp-for="Descripcion" class="control-label"></label>
                    <input type="text" asp-for="Descripcion" class="input-editar form-control" />
                    <span asp-validation-for="Descripcion" class="text-danger"></span>
                </div>
            </div>
        </div>

        <div class="row">
            <div class=" form-group">
                <label asp-for="FaseId" class="control-label"></label>
                <select asp-for="FaseId" asp-items="ViewBag.Fases" class="input-editar-td form-control">
                    <option disabled selected>----Seleccione----</option>
                </select>
                <span asp-validation-for="FaseId" class="text-danger"></span>
            </div>
        </div>

        <br />
        <center>
            <div class="form-group">
                <input type="submit" value="Editar producción" class="btn boton-editar" />
            </div>
        </center>
        <br />
    </form>

</body>

@*<form asp-action="Crear">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="from-group">
            <label asp-for="Nombre" class="control-label"></label>
            <input type="text" asp-for="Nombre" class="form-control"/>
            <span asp-validation-for="Nombre" class="text-danger"></span>
        </div>
    </form>*@
<script src="~/js/site.js"></script>
@await Html.PartialAsync("_ValidationScriptsPartial")

CreacionesPajov/CreacionesPajov/Views/Produccion/Index.cshtml
@model IEnumerable<CreacionesPajov.WEB.Models.Entities.Produccion>

<div class="content">
    <div class="container-fluid">
        <div class="table-responsive">
            <div class="contenedor-index">
                <div class="col-md-7">
                    <h2>Gestión de <b> @ViewBag.Titulo</b></h2>
                </div>
                <br />
                <div class="col-md-7">
                    <a onclick="mostrarModal('@Url.Action("Crear","Produccion",null,Context.Request.Scheme)','Crear producción')" class="btn btn-emp">Crear Producción</a>
                </div>
            </div>

            @if (Model.Count() == 0)
            {
                <br />
                <p>No existen Producciones</p>

            }
            else
            {
                <br />
                <div class="contenedor-tabla">
                    <table class="table table-striped" id="tabla">
                        <thead class="thead-dark">
                            <tr>
                                <th>@Html.DisplayNameFor(model => model.Nombre)</th>
                                <th>@Html.DisplayNameFor(model => model.Descripcion)</th>
                                <th>@Html.DisplayNameFor(model => model.FechaRegistro)</th>
                                <th>@Html.DisplayNameFor(model => model.Fases)</th>
                                @*<th>@Html.DisplayNameFor(model => model.FechaSalida)</th>*@
                                <th>@Html.DisplayNameFor(model => model.Estado)</th>
                                @*<th>@Html.DisplayNameFor(model => model.Fases)</th>*@
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var Produccion in Model)
                            {
                            <tr>
                                <td>@Produccion.Nombre</td>
                                <td>@Produccion.Descripcion</td>
                                <th>@Produccion.FechaRegistro</th>
                                <th>@Produccion.Fases.Nombre</th>
                                @* <th>@Produccion.FechaSalida</th>*@
                                @*<th>@Produccion.Fases.Nombre</th>*@


                                @*<td>@Produccion.Estado</td>*@

                                @if (Produccion.Estado)
                                {
                                    <td><span class="badge badge-act">Habilitado</span></td>
                                }
                                else
                                {
                                    <td><span class="badge badge-desc">Deshabilitado</span></td>
                                }


                                <td>
                                    <a class="text-success" href="javascript:mostrarModal('@Url.Action("Detalle","Produccion",new {id=Produccion.ProduccionId},Context.Request.Scheme)','Detalle Producción')"> <i title="Detalle" class="color-icono1 fa-solid fa-magnifying-glass-plus"></i></a> |
                                    <a href="javascript:mostrarModal('@Url.Action("Editar","Produccion",new {id=Produccion.ProduccionId},Context.Request.Scheme)','Editar Producción')"><i title="Editar" class="color-icono2 fa-solid fa-user-pen"></i>|</a>
                                    @if (Produccion.Estado)
                                    {
                                        <a class="text-success" href="javascript:cambiarEstado('@Url.Action("CambiarEstado","Produccion",new {id=Produccion.ProduccionId},Context.Request.Scheme)')"> <i title="Deshabilitar" class="color-icono1 fa-solid fa-toggle-on"></i></a>
                                    }
                                    else
                                    {
                                        <a class="text-secondary" href="javascript:cambiarEstado('@Url.Action("CambiarEstado","Produccion",new {id=Produccion.ProduccionId},Context.Request.Scheme)')"> <i title="Habilitar" class="color-icono2 fa-solid fa-toggle-off"></i></a>

                                    }



                                </td>

                            </tr>

                            }
                        </tbody>
                    </table>
                </div>
            }

        </div>
    </div>
</div>

@section Scripts{

    <script src="~/js/tabla.js"></script>

    <script>
       @if (TempData["Accion"]!=null && TempData["Accion"].ToString().Equals("Guardar"))
       {
          <text>
            alertify.set('notifier','position','top-right');
            alertify.notify('@TempData["Mansaje"] ', 'success', 5, function( ) {

            });
          </text>
       }
    </script>


}