CreacionesPajov/CreacionesPajov/Models/Entities/DetalleHilo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CreacionesPajov.WEB.Models.Entities
{
    public partial class DetalleHilo
    {
        [Key]
        public int DetalleHiloId { get; set; }
        [Required(ErrorMessage = "El hilo es requerido")]
        [Display(Name = "Hilo")]
        public int? HiloId { get; set; }
        [Required(ErrorMessage = "El control de lote es requerido")]
        [Display(Name = "Control Lote")]
        public int? ControlLoteId { get; set; }

        public virtual ControlLote? ControLote { get; set; }
        public virtual Hilo? Hilo { get; set; }
    }
}

CreacionesPajov/CreacionesPajov/Controllers/DetalleHiloController.cs
using CreacionesPajov.WEB.Models.Abstract.ILoteHilo;
using CreacionesPajov.WEB.Models.DAL;
using CreacionesPajov.WEB.Models.Entities;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CreacionesPajov.WEB.Controllers
{
    public class DetalleHiloController : Controller
    {
        private readonly AppDbContext _Context;
        private readonly ILoteHiloService _loteHiloservice;

        public DetalleHiloController(AppDbContext Context, ILoteHiloService _loteHiloservice)
        {
            this._Context = Context;
            this._loteHiloservice = _loteHiloservice;
        }

        //public IActionResult Index()
        //{

        //    //return await _Context.DetalleHilos.Where(x => x.Hilo).ToListAsync();

        //  //return await _context.Empleados.Where(x => x.Estado).Include(x => x.TiposDocumento).ToListAsync();


        //}


        public IActionResult Crear()

        {
            List<Hilo> hilos = _Context.Hilos.ToList();
            return View(hilos);
        }

        public async Task<IActionResult> Index()
        {
            return View(await _loteHiloservice.ObtenerLote());
        }

        public IActionResult Guardar(HiloViewModel hiloviewmodel)
        {
            using (var transaction = _Context.Database.BeginTransaction())
            {
                try
                {
                    ControlLote controLote = new ControlLote
                    {
                        Total = hiloviewmodel.Total,
                        Descripcion = "Hilo :" + " " + hiloviewmodel.Descripcion
                    };

                    _Context.Add(controLote);
                    _Context.SaveChanges();

                    foreach (Hilo hilo in hiloviewmodel.Hilos)
                    {
                        DetalleHilo detallehilo = new DetalleHilo
                        {
                            HiloId = hilo.HiloId,
                            ControlLoteId = controLote.IdControlLote
                        };
                        _Context.Add(detallehilo);
                    }
                    _Context.SaveChanges();
                    transaction.Commit();
                }
                catch (Exception ex)
                {
                    transaction.Rollback();
                }
            }

            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> ListHilo(int id)
        {
            return View(await _loteHiloservice.ListarHilos(id));
        }
    }
}

CreacionesPajov/CreacionesPajov/Controllers/DetalleTelaController.cs
using CreacionesPajov.WEB.Models.Abstract.ILoteTela;
using CreacionesPajov.WEB.Models.DAL;
using CreacionesPajov.WEB.Models.Entities;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CreacionesPajov.WEB.Controllers
{
    public class DetalleTelaController : Controller
    {
        private readonly AppDbContext _Context;
        private readonly ILoteTelaService _loteTelaservice;

        public DetalleTelaController(AppDbContext Context, ILoteTelaService _loteTelaservice)
        {
            this._Context = Context;
            this._loteTelaservice = _loteTelaservice;
        }

        //public IActionResult Index()
        //{

        //    //return await _Context.DetalleHilos.Where(x => x.Hilo).ToListAsync();

        //  //return await _context.Empleados.Where(x => x.Estado).Include(x => x.TiposDocumento).ToListAsync();


        //}


        public IActionResult Crear()

        {
            List<Tela> telas = _Context.Telas.ToList();
            return View(telas);
        }

        public async Task<IActionResult> Index()
        {

            return View(await _loteTelaservice.ObtenerLote());
        }

        public IActionResult Guardar(TelaViewModel telaviewmodel)
        {
            using (var transaction = _Context.Database.BeginTransaction())
            {
                try
                {
                    ControlLote controLote = new ControlLote
                    {
                        Total = telaviewmodel.Total,
                        Descripcion = "Tela : " +" "+ telaviewmodel.Descripcion
                    };

                    _Context.Add(controLote);
                    _Context.SaveChanges();

                    foreach (Tela tela in telaviewmodel.Telas)
                    {
                        DetalleTela detalletela = new DetalleTela
                        {
                            TelaId = tela.TelaId,
                            ControlLoteId = controLote.IdControlLote
                        };
                        _Context.Add(detalletela);
                    }
                    _Context.SaveChanges();
                    transaction.Commit();
                }
                catch (Exception ex)
                {
                    transaction.Rollback();
                }
            }

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> ListTela(int id)
        {
            return View(await _loteTelaservice.ListarTelas(id));
        }
    }
}

CreacionesPajov/CreacionesPajov/Views/DetalleHilo/Crear.cshtml
@using CreacionesPajov.WEB.Models.Entities
@model List<Hilo>
    <div style="margin: 50px 50px 50px 50px;"class="card">
        <div class="card-body">
            <div class="row">
                <div style="margin-left: 5%;" class="col-4">
                    <div class="form-group">
                        <label>
                            Hilos
                        </label>
                        <select onchange="cantidad(this)" id="HiloId" class="input-crear-det form-control">
                            <option>Seleccione</option>

                            @foreach (Hilo item in Model)
                            {
                            <option cantidad="@item.Cantidad" value="@item.HiloId">@item.Descripcion</option>}
                        </select>
                    </div>

                    <div class="form-group">
                        <label>Cantidad</label>
                        <input readonly type="number" class="input-crear-det form-control" id="Cantidad" />
                    </div>

                    <button onclick="agregar()" class="btn boton-crear" type="button">Agregar</button>
                </div>

                <div style="margin-left: 5%;"class="col-6">
                    <form asp-action="Guardar" method="post">

                        <label>Descripcion Del Lote</label>
                        <input class="input-crear-det-2"name="descripcion" id="Descripcion" />
                        <br />
                        <table id="TablaHilo" class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>
                                        Código Hilo
                                    </th>
                                    <th>
                                        Descripción Hilo
                                    </th>
                                    <th>
                                        Cantidad
                                    </th>

                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td colspan="3" class="text-center">
                                        <h3>Cantidad Hilos: <span id="total"></span> </h3>
                                        <input type="hidden" name="total" id="Total" />
                                    </td>
                                </tr>
                            </tbody>

                            <tfoot>

                            </tfoot>
                        </table>
                        <button type="submit" class="btn boton-crear  btn-block">Guardar </button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    @section Scripts {
    <script>
    function cantidad(e) {
            let _cantidad = $(e).find("option:selected");
            $("#Cantidad").val(_cantidad.attr("cantidad"));
        }

        var cont = 0;
        function agregar() {
            let hilo = $("#HiloId option:selected");
            let total = $("#Total").val() || 0;
            let descripcion = $("#Descripcion").val()
            $("#TablaHilo").append(`
                        <tr>
                            <input type="hidden" name="Hilos[${cont}].HiloId" value="${hilo.val()}"/>
                            <td>${hilo.val()}</td>
                            <td>${hilo.text()}</td>
                            <td>${hilo.attr("cantidad")}</td>
                        </tr>
                        `);

            let suma = parseInt(total) + parseInt(hilo.attr("cantidad"))
            $("#total").text(suma);
            $("#Total").val(suma);
            $("#descripcion").text();
            $("#Descripcion").val();
            cont++;

        }</script>
    }

CreacionesPajov/CreacionesPajov/Views/DetalleHilo/Index.cshtml
@model IEnumerable<CreacionesPajov.WEB.Models.Entities.ControlLote>

<body>  
    <div style="margin: 50px 50px 50px 50px;"><h2>Control de Lote</h2></div>  
    <div style="margin: 30px 100px 100px 100px;">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>
                        #
                    </th>
                    <th>
                        Descripcion
                    </th>

                    <th>
                        Total
                    </th>

                    <th>
                        Fecha Registro
                    </th>
                    <th>
                        Acciones
                    </th>
                </tr>
            </thead>

            @foreach (var ControlLotes in Model)
            {
    <tbody>
        <tr>
            <td>
                @Html.DisplayFor(d => ControlLotes.IdControlLote)
            </td>
            <td>
                @Html.DisplayFor(d => ControlLotes.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(d => ControlLotes.Total)
            </td>
            <td>
                @Html.DisplayFor(d => ControlLotes.FechaRegistro)
            </td>

            <td>
                <a asp-action="ListHilo" asp-route-id="@ControlLotes.IdControlLote" >Listado</a>
            </td>



        </tr>
    </tbody>}
        </table>
        <hr />
        <br />
        <div class="row">
            <div class="col-3">
                <a asp-action="Crear" asp-controller="DetalleHilo" class="btn btn-det">Agregar hilos</a>
            </div>
            <div class="col">
                <a asp-action="Crear" asp-controller="DetalleTela" class="btn btn-det">Agregar telas</a>
            </div>


        </div>
    </div>
</body>

CreacionesPajov/CreacionesPajov/Views/DetalleHilo/ListHilo.cshtml
@using CreacionesPajov.WEB.Models.Entities
@model List<DetalleHilo>


<body>
    <div style="margin: 50px 50px 50px 50px;"><h2>Listado detalle hilo</h2></div>
    <div style="margin: 30px 100px 100px 100px;">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>
                        #
                    </th>
                    <th>
                        Descripcion
                    </th>

                    <th>
                        Cantidad
                    </th>

                </tr>
            </thead>

            @foreach (var DetalleHiloss in Model)
            {
<tbody>
    <tr>
        <td>
            @Html.DisplayFor(i => DetalleHiloss.HiloId)
        </td>
        <td>
            @Html.DisplayFor(i => DetalleHiloss.Hilo.Descripcion)
        </td>
        <td>
            @Html.DisplayFor(i => DetalleHiloss.Hilo.Cantidad)
        </td>
    <tr>

</tbody>            }

        </table>
        <hr />
        <br />
        <div class="row">
            <div class="col-3">
                <a asp-action="Crear" asp-controller="DetalleHilo" class="btn btn-det">Agregar hilos</a>
            </div>
            <div class="col">
                <a asp-action="Crear" asp-controller="DetalleTela" class="btn btn-det">Agregar telas</a>
            </div>


        </div>
    </div>
</body>