CreacionesPajov/CreacionesPajov/Models/Dtos/TipoNovedadEmpleados/TipoNovedadEmpleadoDetalleDto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CreacionesPajov.WEB.Models.Dtos.TipoNovedadEmpleados
{
    public class TipoNovedadEmpleadoDetalleDto
    {
        public int TipoNovedadEmpleadoId { get; set; }
        public string Empleado { get; set; }
        public string Descripcion { get; set; }

    }
}

CreacionesPajov/CreacionesPajov/Models/Dtos/TipoNovedadEmpleados/TipoNovedadEmpleadoDto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CreacionesPajov.WEB.Models.Dtos.TipoNovedadEmpleados
{
    public class TipoNovedadEmpleadoDto
    {
        public int TipoNovedadEmpleadoId { get; set; }


        [Required(ErrorMessage = "El empleado es requerido")]
        [Display(Name = "Empleado")]
        public int? EmpleadoId { get; set; }

        [Required(ErrorMessage = "La Descripción es Obligatoria")]
        [StringLength(50, ErrorMessage = "El {0} debe tener al menos {2} y maximo {1} caracteres", MinimumLength = 4)]
        [Display(Name = "Descripción")]
        public String Descripcion { get; set; }

       
    }
}

CreacionesPajov/CreacionesPajov/Models/Dtos/TipoNovedadEmpleados/TipoNovedadEmpleadoResumenDto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CreacionesPajov.WEB.Models.Dtos.TipoNovedadEmpleados
{
    public class TipoNovedadEmpleadoResumenDto
    {
        public string Empleado { get; set; }
        public string Descripcion { get; set; }
     
    }
}

CreacionesPajov/CreacionesPajov/Models/Entities/TipoNovedadEmpleado.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CreacionesPajov.WEB.Models.Entities
{
    public class TipoNovedadEmpleado
    {
        public int TipoNovedadEmpleadoId { get; set; }

        public virtual Empleado Empleados { get; set; }

        [Required(ErrorMessage = "La fase es requerida")]
        [Display(Name = "Fase")]
        public int? EmpleadoId { get; set; }

        [Required(ErrorMessage = "La descripción es Obligatoria")]
        [StringLength(50, ErrorMessage = "El {0} debe tener al menos {2} y maximo {1} caracteres", MinimumLength = 4)]
        [Display(Name = "Descripción")]
        public String Descripcion { get; set; }


    }
}

CreacionesPajov/CreacionesPajov/Controllers/TipoNovedadEmpleadosController.cs
using CreacionesPajov.WEB.Helpers;
using CreacionesPajov.WEB.Models.Abstract;
using CreacionesPajov.WEB.Models.Abstract.ITipoNovedadEmpleado;
using CreacionesPajov.WEB.Models.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CreacionesPajov.WEB.Controllers
{
    public class TipoNovedadEmpleadosController : Controller
    {
        private readonly ITipoNovedadEmpleadoService _tiponovedadempleadoservice;
        private readonly IEmpleadoService _empleadoService;

        public TipoNovedadEmpleadosController(ITipoNovedadEmpleadoService tiponovedadempleadoservice, IEmpleadoService empleadoService)
        {
            _empleadoService = empleadoService; //inyectamos la interfaz empleadoService.
            _tiponovedadempleadoservice = tiponovedadempleadoservice;
        }

        public async Task<IActionResult> Index()
        {

            @ViewBag.Titulo = "Novedad Empleados";
            var tiponovedadempleados = await _tiponovedadempleadoservice.ObtenerTipoNovedadEmpleados();
            return View(tiponovedadempleados);
        }

        [HttpGet]

        public async Task<IActionResult> Crear()
        {


            try
            {
                ViewBag.Titulo = "Crear Novedad Empleado";
                ViewBag.Empleado = new SelectList(await _empleadoService.ObtenerEmpleados(), "EmpleadoId", "Nombre");
                return View();
            }
            catch (Exception)
            {
                return Json(new { isValid = false, tipoError = "error", mensaje = "Error interno al crear el registro." });

            }


        }

        [HttpPost]

        public async Task<IActionResult> Crear(TipoNovedadEmpleado tiponovedadempleados)
        {
            if (tiponovedadempleados == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _tiponovedadempleadoservice.Crear(tiponovedadempleados);
                    var guardar = await _empleadoService.GaurdarCambios();
                    if (guardar)
                    {

                        //TempData["Accion"] = "Guardar";
                        //TempData["Mansaje"] = $"Se resgistró el empleado {empleado.Nombre}";
                        //return RedirectToAction("Index");
                        return Json(new { isValid = true, operacion = "crear" });
                    }
                    else
                        return Json(new { isValid = false, tipoError = "error", mensaje = "Error interno al crear el registro." });



                }
                catch (Exception)
                {

                    return Json(new { isValid = false, tipoError = "error", mensaje = "Error interno al crear el registro." });
                }

            }
            ViewBag.Titulo = "Crear Novedad Empleado";
            ViewBag.Empleado = new SelectList(await _empleadoService.ObtenerEmpleados(), "EmpleadoId", "Nombre");
            return Json(new { isValid = false, tipoError = "warning", error = "Debe diligencias los campos requeridos.", html = Helper.RenderRazorViewToString(this, "Crear", tiponovedadempleados) });
        }

        [HttpGet]

        public async Task<IActionResult> Detalle(int? id)
        {
            if (id != null)
            {
                try
                {
                    var tiponovedadempleados = await _tiponovedadempleadoservice.ObtenerTipoNovedadEmpleadoPorId(id.Value);
                    if (tiponovedadempleados != null)
                        return View(tiponovedadempleados);
                    else
                        return Json(new { isValid = false, tipoError = "error", mensaje = "Error  al consultar el registro." });

                }
                catch (Exception)
                {

                    return Json(new { isValid = false, tipoError = "error", mensaje = "Error interno al consultar el registro." });

                }
            }
            return Json(new { isValid = false, tipoError = "error", mensaje = "Error  al consultar el registro." });

        }

        [HttpGet]

        public async Task<IActionResult> Editar(int? id)
        {
            if (id != null)
            {
                try
                {
                    var tiponovedadempleados = await _tiponovedadempleadoservice.ObtenerTipoNovedadEmpleadoPorId(id.Value);
                    if (tiponovedadempleados != null)
                    {

                        ViewBag.Empleado = new SelectList(await _empleadoService.ObtenerEmpleados(), "EmpleadoId", "Nombre");

                        return View(tiponovedadempleados);
                    }
                    else
                        return NotFound();
                }
                catch (Exception)
                {

                    throw;
                }
            }
            return NotFound();

        }
        [HttpPost]
        public async Task<IActionResult> Editar(int? id, TipoNovedadEmpleado tiponovedadempleados)
        {
            if (id != tiponovedadempleados.TipoNovedadEmpleadoId)
                return Json(new { isValid = false, tipoError = "error", mensaje = "Error interno al editar el registro." });

            if (ModelState.IsValid)
            {
                try
                {
                    _tiponovedadempleadoservice.Editar(tiponovedadempleados);
                    var editar = await _tiponovedadempleadoservice.GaurdarCambios();
                    if (editar)
                        return Json(new { isValid = true, operacion = "editar" });

                    else
                        return Json(new { isValid = false, tipoError = "error", mensaje = "Error interno al editar el registro." });

                }
                catch (Exception)
                {

                    return Json(new { isValid = false, tipoError = "error", mensaje = "Error interno al editar el registro." });

                }
            }
            //Si el modelo tiene errores en las validadciones
            ViewBag.Titulo = "Editar  Empleado";
            ViewBag.Empleado = new SelectList(await _empleadoService.ObtenerEmpleados(), "EmpleadoId", "Nombre");
            return Json(new { isValid = false, tipoError = "warning", error = "Debe diligencias los campos requeridos.", html = Helper.RenderRazorViewToString(this, "Editar", tiponovedadempleados) });




        }
        //[HttpGet]

        //public async Task<IActionResult> Editar(int? id)
        //{
        //    if (id != null)
        //    {
        //        try
        //        {
        //            var tiponovedadempleados = await _tiponovedadempleadoservice.ObtenerTipoNovedadEmpleadoPorId(id.Value);
        //            if (tiponovedadempleados != null)
        //            {

        //                ViewBag.Empleado = new SelectList(await _empleadoService.ObtenerEmpleados(), "EmpleadoId", "Nombre");

        //                return View(tiponovedadempleados);
        //            }
        //            else
        //                return NotFound();
        //        }
        //        catch (Exception)
        //        {

        //            throw;
        //        }
        //    }
        //    return NotFound();

        //}
        //[HttpPost]
        //public async Task<IActionResult> Editar(int? id, TipoNovedadEmpleado tiponovedadempleados)
        //{
        //    if (id != tiponovedadempleados.TipoNovedadEmpleadoId)
        //        return Json(new { isValid = false, tipoError = "error", mensaje = "Error interno al editar el registro." });

        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            _tiponovedadempleadoservice.Editar(tiponovedadempleados);
        //            var editar = await _tiponovedadempleadoservice.GaurdarCambios();
        //            if (editar)
        //                return Json(new { isValid = true, operacion = "editar" });

        //            else
        //                return Json(new { isValid = false, tipoError = "error", mensaje = "Error interno al editar el registro." });

        //        }
        //        catch (Exception)
        //        {

        //            return Json(new { isValid = false, tipoError = "error", mensaje = "Error interno al editar el registro." });

        //        }
        //    }
        //    //Si el modelo tiene errores en las validadciones
        //    ViewBag.Titulo = "Editar  Novedad Empleado";
        //    ViewBag.Empleado = new SelectList(await _empleadoService.ObtenerEmpleados(), "EmpleadoId", "Nombre");
        //    return Json(new { isValid = false, tipoError = "warning", error = "Debe diligencias los campos requeridos.", html = Helper.RenderRazorViewToString(this, "Editar", tiponovedadempleados) });




        //}
        //[HttpGet]

        //public async Task<IActionResult> CambiarEstado(int? id)
        //{
        //    if (id != null)
        //    {
        //        try
        //        {
        //            var tiponovedadempleados = await _tiponovedadempleadoservice.ObtenerTipoNovedadEmpleadoPorId(id.Value);
        //            if (tiponovedadempleados != null)
        //            {
        //                //tiponovedadempleados.Estado = !tiponovedadempleados.Estado;
        //                //if (empleado.Estado)
        //                //    empleado.Estado = false;
        //                //else
        //                //    empleado.Estado = true;
        //                _tiponovedadempleadoservice.Editar(tiponovedadempleados);
        //                var editar = await _empleadoService.GaurdarCambios();
        //                if (editar)
        //                    return Json(new { isValid = true, });

CreacionesPajov/CreacionesPajov/Views/TipoNovedadEmpleados/Crear.cshtml
@model CreacionesPajov.WEB.Models.Dtos.TipoNovedadEmpleados.TipoNovedadEmpleadoDto

<br />

@{ Layout = null; }

<style>
    span.text-danger.field-validation-error, #EmpleadoId-error, #Descripcion-error {
        font-size: 13px;
    }
</style>

<body style="background-color: #eee;">

    <form asp-action="Crear" id="formulario" onsubmit="return jQueryAjaxPost (this, 'Crear Novedad Empleado','¿Desea crear una Novedad de empleado?'); ">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="row">
            <div class="column">
                <div class="form-group">
                    <label asp-for="EmpleadoId" class="control-label"></label>
                    <select asp-for="EmpleadoId" asp-items="ViewBag.Empleado" class="input-crear form-control">
                        <option disabled selected>----Seleccione----</option>
                    </select>
                    <span asp-validation-for="EmpleadoId" class="text-danger"></span>
                </div>
            </div>
            <div class="column">
                <div class="form-group column2">
                    <label asp-for="Descripcion" class="control-label"></label>
                    <input type="text" asp-for="Descripcion" class="input-crear form-control" />
                    <span asp-validation-for="Descripcion" class="text-danger"></span>
                </div>
            </div>
        </div>
        <br />
        <center>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn boton-crear" />
            </div>
        </center>
        <br />
    </form>
    @*                </div>
            </div>
        </div>*@
</body>

@*<form asp-action="Crear">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="from-group">
            <label asp-for="Nombre" class="control-label"></label>
            <input type="text" asp-for="Nombre" class="form-control"/>
            <span asp-validation-for="Nombre" class="text-danger"></span>
        </div>
    </form>*@
<script src="~/js/site.js"></script>
@await Html.PartialAsync("_ValidationScriptsPartial")

CreacionesPajov/CreacionesPajov/Views/TipoNovedadEmpleados/Detalle.cshtml
@model CreacionesPajov.WEB.Models.Entities.TipoNovedadEmpleado
@{
    Layout = null;
}


<body style="background-color: #eee;">
    <form>
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <center><br />
            <table style="width:650px;" class="detalle table-striped">
                <tbody>
                    <tr>
                        <td><label asp-for="EmpleadoId" class="control-label"></label></td>
                        <td>@Model.Empleados.Nombre</td>
                    </tr>
                    <tr>
                        <td><label asp-for="Descripcion" class="control-label"></label></td>
                        <td>@Model.Descripcion</td>
                    </tr>
                </tbody>
            </table>
        </center>
        <br />
    </form>
    @*              </div>
            </div>
        </div>*@
</body>

<script src="~/js/site.js"></script>
@await Html.PartialAsync("_ValidationScriptsPartial")

CreacionesPajov/CreacionesPajov/Views/TipoNovedadEmpleados/Editar.cshtml
@model CreacionesPajov.WEB.Models.Entities.TipoNovedadEmpleado
@{ Layout = null; }

<style>
    span.text-danger.field-validation-error, #EmpleadoId-error, #Descripcion-error {
        font-size: 13px;
    }
</style>


<h1>@ViewBag.Titulo</h1>
<br />

<input type="hidden" asp-for="TipoNovedadEmpleadoId" />

<body style="background-color: #eee;">

    <form asp-action="Editar" id="formulario" onsubmit="return jQueryAjaxPost(this, 'Editar Novedad Empleado','¿Desea Editar La Novedad Del Empleado?'); ">

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="row">
            <div class="column">
                <div class="form-group">
                    <label asp-for="EmpleadoId" class="control-label"></label>
                    <select asp-for="EmpleadoId" asp-items="ViewBag.Empleado" class="input-editar form-control">
                        <option disabled selected>----Seleccione----</option>
                    </select>
                    <span asp-validation-for="EmpleadoId" class="text-danger"></span>
                </div>
            </div>
            <div class="column">
                <div class="form-group column2">
                    <label asp-for="Descripcion" class="control-label"></label>
                    <input type="text" asp-for="Descripcion" class="input-editar form-control" />
                    <input type="hidden" asp-for="TipoNovedadEmpleadoId" />
                    <span asp-validation-for="Descripcion" class="text-danger"></span>
                </div>
            </div>
        </div>
        <br />
        <center>
            <div class="form-group">
                <input type="submit" value="Editar Novedad Empleado" class="btn boton-editar" />
            </div>
        </center>
        <br />
    </form>

</body>

@*<form asp-action="Crear">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="from-group">
            <label asp-for="Nombre" class="control-label"></label>
            <input type="text" asp-for="Nombre" class="form-control"/>
            <span asp-validation-for="Nombre" class="text-danger"></span>
        </div>
    </form>*@
<script src="~/js/site.js"></script>
@await Html.PartialAsync("_ValidationScriptsPartial")

CreacionesPajov/CreacionesPajov/Views/TipoNovedadEmpleados/Index.cshtml
@model IEnumerable<CreacionesPajov.WEB.Models.Entities.TipoNovedadEmpleado>
@section Styles{

}
<div class="content">
    <div class="container-fluid">
        <div class="table-responsive">
            <div class="contenedor-index">
            <div class="col-md-7">
                <h2>Gestión de <b> @ViewBag.Titulo</b></h2>
            </div>
            <br />
            <div class="col-md-7">
                <a onclick="mostrarModal('@Url.Action("Crear","TipoNovedadEmpleados",null,Context.Request.Scheme)','Crear Novedad Empleado')" class="btn btn-emp">Crear novedad empleado</a>
            </div>
            </div>

            @if (Model.Count() == 0)
            {
                <br />
                <p>No existen Novedades De Empleado</p>
            }
            else
            {
                <br />
                <div class="contenedor-tabla">
                <table class="table table-striped" id="tabla">
                    <thead class="thead-dark">
                        <tr>
                            <th>@Html.DisplayNameFor(model => model.EmpleadoId)</th>
                            <th>@Html.DisplayNameFor(model => model.Descripcion)</th>
                         
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var tiponovedadempleado in Model)
                        {
                            <tr>
                                <td>@tiponovedadempleado.Empleados.Nombre</td>
                                <td>@tiponovedadempleado.Descripcion</td>

                              

                                <td>
                                    <a class="text-success" href="javascript:mostrarModal('@Url.Action("Detalle","TipoNovedadEmpleados",new {id=tiponovedadempleado.TipoNovedadEmpleadoId},Context.Request.Scheme)','Detalle novedad empleado')"> <i title="Detalle" class="color-icono1 fa-solid fa-magnifying-glass-plus"></i></a> |
                                    <a href="javascript:mostrarModal('@Url.Action("Editar","TipoNovedadEmpleados",new {id=tiponovedadempleado.TipoNovedadEmpleadoId},Context.Request.Scheme)','Editar novedad empleado')"><i title="Editar" class="color-icono2 fa-solid fa-user-pen"></i>|</a>
                                    



                                </td>
                            </tr>

                        }
                    </tbody>
                </table>
                    </div>
            }

        </div>
    </div>
</div>




@section Scripts{

    <script src="~/js/tabla.js"></script>

    <script>
       @if (TempData["Accion"]!=null && TempData["Accion"].ToString().Equals("Guardar"))
       {
          <text>
            alertify.set('notifier','position','top-right');
            alertify.notify('@TempData["Mansaje"] ', 'success', 5, function( ) {

            });
          </text>
       }
    </script>


}