CreacionesPajov/CreacionesPajov/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using static CreacionesPajov.WEB.Helpers.Helper;

namespace CreacionesPajov.WEB.Controllers
{

    public class AdminController : Controller
    {
        [NoDirectAccess]
        [Authorize]
        public IActionResult Index()
        {
            return View();
        }
        [NoDirectAccess]
        [Authorize]
        public IActionResult  DashBoard()
        {
            return View();
        }
        [NoDirectAccess]
        public IActionResult NoAutorizado()
        {
            return View();
        }
    }

}

CreacionesPajov/CreacionesPajov/Controllers/HiloController.cs
using CreacionesPajov.WEB.Helpers;
using CreacionesPajov.WEB.Models.Abstract.IColorHilo;
using CreacionesPajov.WEB.Models.Abstract.IHilos;
using CreacionesPajov.WEB.Models.Abstract.IProveedorHilo;
using CreacionesPajov.WEB.Models.Bussines;
using CreacionesPajov.WEB.Models.DAL;
using CreacionesPajov.WEB.Models.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CreacionesPajov.WEB.Controllers
{
    public class HiloController : Controller
    {

        private readonly IHilosService _hilosService;

        private readonly IProveedorHiloService _proveedorHilo;

        private readonly IColorHiloService _colorHiloService;

        public HiloController(IHilosService hilosService, IProveedorHiloService proveedorHilo, IColorHiloService colorHiloService)
        {
            _hilosService = hilosService; //inyectamos la interfaz empleadoService.
            _proveedorHilo = proveedorHilo;
            _colorHiloService = colorHiloService;
        }
        public async Task<IActionResult> Index()
        {

            @ViewBag.Titulo = "Hilos";
            var hilos = await _hilosService.ObtenerHilo();
            return View(hilos);
        }


        //Index de Stanly a traves de una lista
        //public async Task<IActionResult> Index()
        //{
        //    List<Hilo> hilos = await _AppDbContext.Hilos.ToListAsync();
        //    return View(hilos);

        //}

        [HttpGet]
        public async Task<IActionResult> Crear()
        {


            try
            {
                ViewBag.Titulo = "Crear hilo";
                ViewBag.TiposProveedores = new SelectList(await _proveedorHilo.ObtenerProveedorHilos(), "ProveedorHiloId", "Nombre");
                ViewBag.ColoresHilos = new SelectList(await _colorHiloService.ObtenerColorHilos(), "ColorHiloId", "Nombre");
                return View();
            }
            catch (Exception)
            {
                return Json(new { isValid = false, tipoError = "error", mensaje = "Error interno al crear el registro." });

            }


        }
        [HttpPost]

        public async Task<IActionResult> CrearAsync(Hilo hilo)
        {
            if (hilo == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _hilosService.Crear(hilo);
                    var guardar = await _hilosService.GuardarCambios();
                    if (guardar)
                    {


                        return Json(new { isValid = true, operacion = "crear" });
                    }
                    else
                        return Json(new { isValid = false, tipoError = "error", mensaje = "Error interno al crear el registro." });



                }
                catch (Exception)
                {

                    return Json(new { isValid = false, tipoError = "error", mensaje = "Error interno al crear el registro." });
                }

            }
            ViewBag.Titulo = "Crear hilo";

            return Json(new { isValid = false, tipoError = "warning", error = "Debe diligenciar los campos requeridos.", html = Helper.RenderRazorViewToString(this, "Crear", hilo) });
        }

        [HttpGet]

        public async Task<IActionResult> Editar(int? id)
        {
            if (id != null)
            {
                try
                {
                    var hilo = await _hilosService.ObtenerHiloPorId(id.Value);
                    if (hilo!= null)
                    {
                        ViewBag.TiposProveedores = new SelectList(await _proveedorHilo.ObtenerProveedorHilos(), "ProveedorHiloId", "Nombre");
                        ViewBag.ColoresHilos = new SelectList(await _colorHiloService.ObtenerColorHilos(), "ColorHiloId", "Nombre");
                        ViewBag.Hilo = new SelectList(await _hilosService.ObtenerHilo(), "Descripción");

                        return View(hilo);
                    }
                    else
                        return NotFound();
                }
                catch (Exception)
                {

                    throw;
                }
            }
            return NotFound();

        }
        [HttpPost]

        public async Task<IActionResult> Editar(int? id, Hilo hilo)
        {
            if (id != hilo.HiloId)
                return Json(new { isValid = false, tipoError = "error", mensaje = "Error interno al editar el registro." });

            if (ModelState.IsValid)
            {
                try
                {
                    _hilosService.Editar(hilo);
                    var editar = await _hilosService.GuardarCambios();
                    if (editar)
                        return Json(new { isValid = true, operacion = "editar" });

                    else
                        return Json(new { isValid = false, tipoError = "error", mensaje = "Error interno al editar el registro." });

                }
                catch (Exception)
                {

                    return Json(new { isValid = false, tipoError = "error", mensaje = "Error interno al editar el registro." });

                }
            }
            //Si el modelo tiene errores en las validadciones
            ViewBag.Titulo = "Editar  hilo";
            ViewBag.Hilo = new SelectList(await _hilosService.ObtenerHilo(), "Descripción");
            return Json(new { isValid = false, tipoError = "warning", error = "Debe diligenciar los campos requeridos.", html = Helper.RenderRazorViewToString(this, "Editar", hilo) });


        }

        [HttpGet]

        public async Task<IActionResult> Detalle(int? id)
        {
            if (id != null)
            {
                try
                {
                    ViewBag.TiposProveedores = new SelectList(await _proveedorHilo.ObtenerProveedorHilos(), "ProveedorHiloId", "Nombre");
                    ViewBag.ColoresHilos = new SelectList(await _colorHiloService.ObtenerColorHilos(), "ColorHiloId", "Nombre");
                    var hilo = await _hilosService.ObtenerHiloPorId(id.Value);
                    if (hilo != null)
                        return View(hilo);
                    else
                        return Json(new { isValid = false, tipoError = "error", mensaje = "Error  al consultar el registro." });

                }
                catch (Exception)
                {

                    return Json(new { isValid = false, tipoError = "error", mensaje = "Error interno al consultar el registro." });

                }
            }
            return Json(new { isValid = false, tipoError = "error", mensaje = "Error  al consultar el registro." });

        }

       



    }
}

CreacionesPajov/CreacionesPajov/Controllers/ReportesController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Rotativa.AspNetCore;
using CreacionesPajov.WEB.Models.Abstract;

namespace CreacionesPajov.WEB.Controllers
{
    public class ReportesController : Controller
    {

        private readonly IEmpleadoService _empleadoService;
        private readonly ITipoDocumentoService _tipoDocumentoService;

        public ReportesController(IEmpleadoService empleadoService, ITipoDocumentoService tipoDocumentoService)
        {
            _empleadoService = empleadoService; //inyectamos la interfaz empleadoService.
            _tipoDocumentoService = tipoDocumentoService;
        }

        public async Task<IActionResult> Index()
        {
            var empleados = await _empleadoService.ObtenerEmpleados();
            return new ViewAsPdf("Index", empleados) { 
            
            };
        }

    }
}

CreacionesPajov/CreacionesPajov/Controllers/TelaController.cs
using CreacionesPajov.WEB.Helpers;
using CreacionesPajov.WEB.Models.Abstract.IColorTela;
using CreacionesPajov.WEB.Models.Abstract.IProveedorTela;
using CreacionesPajov.WEB.Models.Abstract.ITelas;
using CreacionesPajov.WEB.Models.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CreacionesPajov.WEB.Controllers
{
    public class TelaController : Controller
    {
        private readonly ITelasService _telasService;

        private readonly IProveedorTelaService _proveedorTela;

        private readonly IColorTelaService _colorTelaService;

        public TelaController(ITelasService telasService, IProveedorTelaService proveedorTela, IColorTelaService colorTelaService)
        {
            _telasService = telasService; //inyectamos la interfaz empleadoService.
            _proveedorTela = proveedorTela;
            _colorTelaService = colorTelaService;
        }
        public async Task<IActionResult> Index()
        {

            @ViewBag.Titulo = "Telas";
            var telas = await _telasService.ObtenerTela();
            return View(telas);
        }


        //Index de Stanly a traves de una lista
        //public async Task<IActionResult> Index()
        //{
        //    List<Hilo> hilos = await _AppDbContext.Hilos.ToListAsync();
        //    return View(hilos);

        //}

        [HttpGet]
        public async Task<IActionResult> Crear()
        {


            try
            {
                ViewBag.Titulo = "Crear tela";
                ViewBag.ProveedorTelas = new SelectList(await _proveedorTela.ObtenerProveedorTelas(), "ProveedorTelaId", "Nombre");
                ViewBag.ColoresTelas = new SelectList(await _colorTelaService.ObtenerColorTelas(), "ColorTelaId", "Nombre");
                return View();
            }
            catch (Exception)
            {
                return Json(new { isValid = false, tipoError = "error", mensaje = "Error interno al crear el registro." });

            }


        }
        [HttpPost]

        public async Task<IActionResult> CrearAsync(Tela tela)
        {
            if (tela == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _telasService.Crear(tela);
                    var guardar = await _telasService.GuardarCambios();
                    if (guardar)
                    {


                        return Json(new { isValid = true, operacion = "crear" });
                    }
                    else
                        return Json(new { isValid = false, tipoError = "error", mensaje = "Error interno al crear el registro." });



                }
                catch (Exception)
                {

                    return Json(new { isValid = false, tipoError = "error", mensaje = "Error interno al crear el registro." });
                }

            }
            ViewBag.Titulo = "Crear tela";

            return Json(new { isValid = false, tipoError = "warning", error = "Debe diligenciar los campos requeridos.", html = Helper.RenderRazorViewToString(this, "Crear", tela) });
        }

        [HttpGet]

        public async Task<IActionResult> Editar(int? id)
        {
            if (id != null)
            {
                try
                {

                    var tela = await _telasService.ObtenerTelaPorId(id.Value);
                    if (tela != null)
                    {
                        ViewBag.ProveedorTelas = new SelectList(await _proveedorTela.ObtenerProveedorTelas(), "ProveedorTelaId", "Nombre");
                        ViewBag.ColoresTelas = new SelectList(await _colorTelaService.ObtenerColorTelas(), "ColorTelaId", "Nombre");

                        ViewBag.Tela = new SelectList(await _telasService.ObtenerTela(), "Descripción");

                        return View(tela);
                    }
                    else
                        return NotFound();
                }
                catch (Exception)
                {

                    throw;
                }
            }
            return NotFound();

        }
        [HttpPost]

        public async Task<IActionResult> Editar(int? id, Tela tela)
        {
            if (id != tela.TelaId)
                return Json(new { isValid = false, tipoError = "error", mensaje = "Error interno al editar el registro." });

            if (ModelState.IsValid)
            {
                try
                {
                    _telasService.Editar(tela);
                    var editar = await _telasService.GuardarCambios();
                    if (editar)
                        return Json(new { isValid = true, operacion = "editar" });

                    else
                        return Json(new { isValid = false, tipoError = "error", mensaje = "Error interno al editar el registro." });

                }
                catch (Exception)
                {

                    return Json(new { isValid = false, tipoError = "error", mensaje = "Error interno al editar el registro." });

                }
            }
            //Si el modelo tiene errores en las validadciones
            ViewBag.Titulo = "Editar  tela";
            ViewBag.Tela = new SelectList(await _telasService.ObtenerTela(), "Descripción");
            return Json(new { isValid = false, tipoError = "warning", error = "Debe diligenciar los campos requeridos.", html = Helper.RenderRazorViewToString(this, "Editar", tela) });


        }

        [HttpGet]

        public async Task<IActionResult> Detalle(int? id)
        {
            if (id != null)
            {
                try
                {
                    ViewBag.ProveedorTelas = new SelectList(await _proveedorTela.ObtenerProveedorTelas(), "ProveedorTelaId", "Nombre");
                    ViewBag.ColoresTelas = new SelectList(await _colorTelaService.ObtenerColorTelas(), "ColorTelaId", "Nombre");
                    var hilo = await _telasService.ObtenerTelaPorId(id.Value);
                    if (hilo != null)
                        return View(hilo);
                    else
                        return Json(new { isValid = false, tipoError = "error", mensaje = "Error  al consultar el registro." });

                }
                catch (Exception)
                {

                    return Json(new { isValid = false, tipoError = "error", mensaje = "Error interno al consultar el registro." });

                }
            }
            return Json(new { isValid = false, tipoError = "error", mensaje = "Error  al consultar el registro." });

        }
 }
}

CreacionesPajov/CreacionesPajov/Views/Shared/_Footer.cshtml
<footer>




</footer> 

CreacionesPajov/CreacionesPajov/Views/Shared/_Navbar.cshtml
<style>
</style>

<nav class="main-header navbar navbar-expand navbar-white navbar-light">

    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a asp-action="DashBoard" asp-controller="Admin"  class="nav-link">Dash</a>
        </li>

    </ul>

    <ul class="navbar-nav ml-auto">

        <li class="nav-item">
            <div class="navbar-search-block">
                <form class="form-inline">
                    <div class="input-group input-group-sm">
                        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                        <div class="input-group-append">


                        </div>
                    </div>
                </form>
            </div>
        </li>


        <li class="nav-item dropdown user-menu">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
                <i class="fa-solid fa-arrow-up-right-from-square"></i>
            </a>
            <ul class="dropdown-menu dropdown-menu-lg dropdown-menu-right">

                <li class="user-header bg-primary">
                    <img src="~/adminlte/dist/img/logout.png" style="margin-left: -13px; margin-top:-20px; width: 110%; height:125%" />
                </li>


                <li class="user-footer">
                    <a asp-action="CerrarSesion" asp-controller="Usuarios" class="btn btn-default btn-flat float-right">Cerrar sesión</a>
                </li>
            </ul>
        </li>








        <li class="nav-item">
            <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                <i class="fas fa-expand-arrows-alt"></i>
            </a>
        </li>

    </ul>
</nav>

CreacionesPajov/CreacionesPajov/Views/Shared/_Sidebar.cshtml
<aside class="main-sidebar sidebar-dark-primary elevation-4">

    <a href="index3.html" class="brand-link">
        <img src="~/adminlte/dist/img/byn.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">Creaciones Pajov</span>
    </a>

    <div class="sidebar">

    

        @*   <div class="form-inline">
                <div class="input-group" data-widget="sidebar-search">
                    <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
                    <div class="input-group-append">
                        <button class="btn btn-sidebar">
                            <i class="fas fa-search fa-fw"></i>
                        </button>
                    </div>
                </div>
            </div>*@

        <nav class="mt-2">

            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">

                <li class="nav-item ">
                    <a class="nav-link ">
                        <i class="fa-solid fa-house-user"></i>
                        <p>
                            Administradores
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a asp-action="Index" asp-controller="Usuarios" class="nav-link  active">
                                <i class="fa-solid fa-users"></i>
                                <p>Usuarios</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-action="Index" asp-controller="Roles" class="nav-link active">
                                <i class="fa-solid fa-id-card"></i>
                                <p>Crear roles</p>
                            </a>
                        </li>
                    </ul>
                </li>




                <li class="nav-item">
                    <a asp-action="Index" asp-controller="Empleados" class="nav-link">
                        <i class="fa-solid fa-users-gear"></i>
                        <p>
                            Empleados
                        </p>
                    </a>
                </li>

                <li class="nav-item ">
                    <a class="nav-link ">
                        <i class="fa-solid fa-user-tie"></i>
                        <p>
                            Proveedores
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a asp-action="Index" asp-controller="ProveedorTelas" class="nav-link  active">
                                <i class="fas fa-brush"></i>
                                <p>Proveedor de telas</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-action="Index" asp-controller="ProveedorHilos" class="nav-link active">
                                <i class="fas fa-paint-brush"></i>
                                <p>Proveedor de hilos</p>
                            </a>
                        </li>
                    </ul>
                </li>


                <li class="nav-item ">
                    <a class="nav-link">
                        <i class="fa-solid fa-fax"></i>
                        <p>
                            Producción
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a asp-action="Index" asp-controller="Produccion" class="nav-link active">
                                <i class="fa-solid fa-check-to-slot"></i>
                                <p>
                                    Producción
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-action="Index" asp-controller="Operaciones" class="nav-link active">
                                <i class="fa-solid fa-gear"></i>
                                <p>
                                    Operaciones
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-action="Index" asp-controller="Fases" class="nav-link active">
                                <i class="fa-solid fa-border-all"></i>
                                <p>
                                    Fases
                                </p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a asp-action="Index" asp-controller="SubFases" class="nav-link active">
                                <i class="fa-solid fa-border-none"></i>
                                <p>
                                    SubFases
                                </p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a asp-action="Index" asp-controller="Remisiones" class="nav-link active">
                                <i class="fa-brands fa-wpforms"></i>
                                <p>
                                    Remisiones
                                </p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a asp-action="Index" asp-controller="ColorTelas" class="nav-link active">
                                <i class="fas fa-brush"></i>
                                <p>
                                    Color Telas
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-action="Index" asp-controller="ColorHilos" class="nav-link active">
                                <i class="fa-solid fa-paintbrush"></i>
                                <p>
                                    Color Hilos
                                </p>
                            </a>
                        </li>



                        <li class="nav-item">
                            <a asp-action="Index" asp-controller="TipoPrendas" class="nav-link active">
                                <i class="fa-solid fa-shirt"></i>
                                <p>
                                    Tipo Prendas
                                </p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a asp-action="Index" asp-controller="Hilo" class="nav-link active">

                                <i class="fa-solid fa-scissors"></i>
                                <p>
                                    Hilos
                                </p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a asp-action="Index" asp-controller="Tela" class="nav-link active">

                                <i class="fa-solid fa-shirt"></i>
                                <p>
                                    Telas
                                </p>
                            </a>
                        </li>


                        <li class="nav-item">
                            <a asp-action="Index" asp-controller="DetalleHilo" class="nav-link active">

                                <i class="fa-solid fa-check-to-slot"></i>
                                <p>
                                    Control Lotes: hilos
                                </p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a asp-action="Index" asp-controller="DetalleTela" class="nav-link active">

                                <i class="fa-solid fa-check-to-slot"></i>
                                <p>
                                    Control Lotes: telas
                                </p>
                            </a>
                        </li>


                    </ul>
                </li>

                <li class="nav-item ">
                    <a class="nav-link ">
                        <i class="fa-solid fa-circle-exclamation"></i>
                        <p>
                            Novedades
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a asp-action="Index" asp-controller="TipoNovedadEmpleados" class="nav-link  active">
                                <i class="fa-solid fa-bell"></i>
                                <p>Novedades de empleados</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item ">
                    <a class="nav-link ">
                        <i class="fa-solid fa-user-tie"></i>
                        <p>
                            Reportes
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a asp-action="Index" asp-controller="Reportes" class="nav-link  active">
                                <i class="fas fa-brush"></i>
                                <p>Reportes Empleados Habilitados</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-action="Index" asp-controller="ReportesEmpleadosInactivos" class="nav-link active">
                                <i class="fas fa-paint-brush"></i>
                                <p>Reportes Empleados Inhabilitados</p>
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>

        </nav>
    </div>
</aside>

<aside class="control-sidebar control-sidebar-dark">
    <div class="p-3">
        <h5>Title</h5>
        <p>Sidebar content</p>
    </div>
</aside>